shiny:
  image:
    repository: avouacr/batuc-trainer
    tag: "0.0.1"
  ingress:
    enabled: true
    hostname: batuc-trainer.lab.sspcloud.fr
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
